fix: remove unused positional argument
In this commit:
- remove unused positional argument that was causing error: `TypeError: PeerInstructionXBlock.parse_xml() missing 1 required positional argument: 'id_generator'`
- bump version